### ISSUE TITLE
Feature Proposal: Delayed tween start/duration as range

### ISSUE THREAD

**Issue by ten3roberts** [sanbox-irl/tween#5]
E.g:

```rust
use tween::Tweener;

/// Sine in which is `0` for the first two seconds
let mut tweener = Tweener::sine_in_out(0, 100, 2.0..5.0);
let mut position = 0;

const DT: f32 = 1.0 / 60.0;

// and then in your main loop...
loop {
    position = tweener.move_by(DT);
    println!("{position}");
    if tweener.is_finished() {
        break;
    }
}

assert_eq!(position, 100, "we've moved to the end of the tween");
```

As `Tweener` already clamps the `t` value between 0 and 1 it could be implemented by implementing `Time` for range types.

**Comment by sanbox-irl** [comment]
Intriguing idea, but you can actually already do this without changing the api:

```
tweener.move_to(-2.0);

// and then in your main loop...
loop {
    position = tweener.move_by(DT);
    
    if tweener.is_started() {
            println!("{position}");
    }

    if tweener.is_ended() {
            break;
    }
}

```

**Comment by sanbox-irl** [comment]
the `is started` is basically there for exactly this pattern

**Comment by ten3roberts** [comment]
Splendid.

Perhaps a method like `new_at` could be added to simplify creating a tween, and moving it, without having to use a `let mut` statement,  I.e; allow chaining and easier creation.

P.S: I like the new api in 2.0 :+1:

**Comment by sanbox-irl** [comment]
Let me know if this is sufficient and I'll go ahead and close this?

https://github.com/sanbox-irl/tween/commit/751173fc091a5f58758ccf6d1500bc12355767be
